language: node_js
os:
- linux
dist: focal
node_js:
- '18'
python:
- '3.7'
cache:
  pip: true
install: skip
before_script:
- npm install grunt-cli -g
- ruby -v
- gem -v
- gem update --system
- gem install sass
script: sleep 10
