os: linux
dist: xenial
language: csharp
mono:
  - none
dotnet:
  - 3.1.401
install: skip
script: sleep 10

deploy:
  provider: script
  edge:
    branch: v2.0.3-beta.4
  on:
    all_branches: true
  script: ruby -v
